cluster:
  name: 'my-cluster'
  region: 'us-east-1'

image:
  repository: 'fluent/fluentd-kubernetes-daemonset'
  pullPolicy: 'IfNotPresent'
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'v1.12.2-debian-cloudwatch-1.3'

namespace: ""

serviceAccount:
  create: true
  annotations: {}
  name: "fluentd"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
