{{- if not .Values.datadog.appKeyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog.fullname" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  app-key: {{ default "MISSING" .Values.datadog.appKey | b64enc | quote }}
{{- else }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: 'datadog-app'
  namespace: monitoring
type: Opaque
spec:
  backendType: 'secretsManager'
  data:
    - key: 'datadog/app'
      name: 'app-key'
{{- end }}