---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: icario-runner
  namespace: github
spec:
  replicas: "{{ .Values.replicas }}"
  template:
    spec:
      organization: "{{ .Values.github.organization }}"
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      serviceAccountName: gh-runner
      securityContext:
        fsGroup: 1001
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      dockerEnabled:  false
      dockerdWithinRunnerContainer: true
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

