{{- if .Values.admin.externalSecret }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: 'grafana'
  namespace: 'tools'
type: 'Opaque'
spec:
  backendType: 'systemManager'
  data:
    - key: {{ .Values.admin.externalSecret.password.key }}
      name: 'admin-password'
    - key: {{ .Values.admin.externalSecret.user.key }}
      name: 'admin-user'
    - key: {{ .Values.admin.externalSecret.oidc.id }}
      name: 'clientId'
    - key: {{ .Values.admin.externalSecret.oidc.secret }}
      name: 'clientSecret'
{{ end }}