---
github:
  organization: ""
  namespace: ""

image:
  repository: "summerwind/actions-runner"
  tag: "v2.277.1"


replicas: 1

resources: {}

scaling:
  replicas:
    max: 15
    min: 5
  scaledown:
    delay: 60

tolerations: {}
