---
# dind:
#   enabled: false
#   runnercontainer: true

github:
  organization: ""
  namespace: ""

image:
  repository: 'summerwind/actions-runner'
  tag: 'v2.278.0'


replicas:
  count: 10

resources: {}

scaling:
  replicas:
    max: 15
    min: 5
  scaledown:
    delay: 60

serviceAccount:
  create: true
  annotations: {}

tolerations: {}
