{{- if or .Values.monitor_istio .Values.monitor_service_accounts .Values.collect_pod_labels .Values.microsegmentation }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cluster_role_name }}
rules:
{{- if .Values.monitor_service_accounts}}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"] # Allow Defenders to list RBAC resources
  verbs: ["list"]
{{- end}}
{{- if .Values.monitor_istio}}
- apiGroups: ["rbac.istio.io"]
  resources: ["rbacconfigs", "servicerolebindings", "serviceroles"] # Allow Defenders to list Istio RBAC resources
  verbs: ["list"]
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies"] # Allow Defenders to list Istio authorization policies
  verbs: ["list"]
- apiGroups: ["authentication.istio.io"]
  resources: ["meshpolicies"] # Allow Defenders to list Istio mesh policies
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways", "serviceentries"] # Allow Defenders to list Istio networking resources
  verbs: ["list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "endpoints", "services"] # Allow Defenders to list pods, services and endpoints
  verbs: ["list"]
{{- end}}
{{- if .Values.collect_pod_labels}}
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"] # Allow Defenders to get Deployments and ReplicaSets
  verbs: ["get"]
- apiGroups: [""] # Core API
  resources: ["namespaces", "pods"] # Allow Defenders to get Namespaces and Pods
  verbs: ["get"]
{{- end}}
{{- if .Values.microsegmentation}}
- apiGroups: [""] 
  resources: ["nodes"] 
  verbs: ["get"]
- apiGroups: [""] 
  resources: ["pods"] 
  verbs: ["get", "list", "watch"] 
- apiGroups: [""] 
  resources: ["events"] 
  verbs: ["create", "patch", "update"]
{{- end}}
{{- end}}