apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: twistlock-secrets2
  namespace: twistlock
type: Opaque
spec:
  backendType: 'secretsManager'
  dataFrom:
    - '/prismacloud-defender'