apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: 'polaris-oidc'
  namespace: 'tools'
type: 'Opaque'
spec:
  backendType: 'systemManager'
  data:
    - key: '/eks/polaris/client_id'
      name: 'clientId'
    - key: '/eks/polaris/client_secret'
      name: 'clientSecret'